spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PWD}

server:
  error:
    include-stacktrace: never


api:
  security:
    token:
      secret: ${JWT_SECRET}